Lenguajes/Python/Django/djangoYPymongo/djangouser-master/DjangoM7/DjangoM7/urls.py
from django.contrib import admin
from django.urls import path, include, path

import frasesmiticas

urlpatterns = [
    path('admin/', admin.site.urls),
    path('frasesmiticas/', include('frasesmiticas.urls'), name='frasesmiticas'),
]

Lenguajes/Python/Django/djangoYPymongo/djangouser-master/DjangoM7/frasesmiticas/urls.py
from django.urls import path
from . import views



app_name = "frasesmiticas"
urlpatterns = [
    path('', views.index, name="index"),
    path('gordo', views.kilos, name="kilos"),
    path('addFrase', views.addFrase, name="addFrase"),
    path('postAddFrase', views.postAddFrase, name="postAddFrase"),
    path('fraseRandom', views.fraseRandom, name="fraseRandom"), #fraseRandomNSFW
    path('fraseRandomSFW', views.fraseRandomSFW, name="fraseRandomSFW"),
    path('frasesDe/<str:nombre>/', views.frasesDe, name="frasesDe"),
    path('fraseDe/<str:nombre>/', views.fraseDe, name="fraseDe"),
    path('addTag/<int:id>/', views.addTag, name="addTag"),
    path('addTagPost/<int:idF>/', views.addTagPost, name="addTagPost"),
    path('removeTag/<int:idF>/<str:nomTag>', views.removeTag, name="removeTag")

]

Lenguajes/Python/Django/djangoYPymongo/djangouser-master/DjangoM7/frasesmiticas/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings


class User(AbstractUser):
    nFrases = models.IntegerField(default=0)


class Tag(models.Model):
    nombre_tag = models.CharField(max_length=50, unique=True)
    nsfw = models.BooleanField(default=False)

class Frase(models.Model):
    texto_frase = models.CharField(max_length=500)
    data = models.DateTimeField('fecha frase')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='frasesu')
    tags = models.ManyToManyField(Tag, related_name='frases')

Lenguajes/Python/Django/djangoYPymongo/djangouser-master/DjangoM7/frasesmiticas/views.py
from django.shortcuts import render

# Create your views here.
from .models import Frase, Tag, User
import datetime
import random

from django.http import HttpResponse

def index(request):
    return HttpResponse("/addFrase <br> /fraseRandom <br>")

def kilos(request):
    return HttpResponse("iker ha hecho mucho ejercicio, well done")

def addFrase(request):
    return render(request, 'frasesmiticas/addFrase.html')


def postAddFrase(request):
    #request.POST["frase"]
    #request.POST["user"]
    m_user = User()
    m_user = User.objects.get(username=request.POST["user"])
    m_user.nFrases = m_user.nFrases + 1
    m_user.save()

    frase = Frase(texto_frase=request.POST["frase"], data=datetime.date.today(),user=m_user)
    frase.save()

    return HttpResponse("Introducida la frase: "+request.POST["frase"]+" del usuario: "+request.POST["user"])

def fraseRandom(request):
    all_entries = Frase.objects.all()
    r_frase = random.choice(all_entries)
    return HttpResponse(r_frase.texto_frase);

def fraseRandomSFW(request):
    all_entries = Frase.objects.filter()

    iker = (list(all_entries))
    random.shuffle(iker)

    chek = True
    for r_frase in iker:
        chek = False
        for tag in r_frase.tags.all():
            if tag.nsfw == True:
                chek = True


        if chek == False:

            return HttpResponse(r_frase.texto_frase);

    return HttpResponse("lo sentimos no hay frases family friendly");





def frasesDe(request, nombre):
    sus = User()
    try:
        sus = User.objects.get(username = nombre)
        try:
            frase = Frase.objects.filter(user=sus)
            return render(request, 'frasesmiticas/frasesDe.html', {'frases': frase, 'usuario': sus})
        except frase.DoesNotExist:
            return HttpResponse("No existen frases.")
    except sus.DoesNotExist:
        return HttpResponse("No existe ese usuario.")

def fraseDe(request, nombre):
    sus = User()
    try:
        sus = User.objects.get(username=nombre)
        try:
            frase = random.choice(Frase.objects.filter(user=sus))
            return HttpResponse("Frase aleatoria de "+ sus.username + ": <br>" + frase.texto_frase+"<br> -"+frase.user.username+ ", "+str(frase.data.year))
        except frase.DoesNotExist:
            return HttpResponse("No existen frases.")
    except sus.DoesNotExist:
        return HttpResponse("No existe ese usuario.")

def addTag(request, id):
    tags = Tag.objects.filter()

    frase = Frase()
    try:
        frase = Frase.objects.get(id=id)  # get porque solo necesito 1
    except frase.DoesNotExist:
        return HttpResponse("No existe esa frase.")

    return render(request, 'frasesmiticas/addTag.html', {'tags': tags, 'frase':frase})


def addTagPost(request, idF):

    tag = Tag()

    try:
        tag = Tag.objects.get(id=request.POST["choice"])
        frase = Frase()
        try:
            frase = Frase.objects.get(id=idF)

            frase.tags.add(tag)


            frase.save()
            return HttpResponse("Tag añadido")
        except frase.DoesNotExist:
            return HttpResponse("error.")
    except tag.DoesNotExist:
        return HttpResponse("error.")



def removeTag(request, idF, nomTag):

    tag = Tag()

    try:
        tag = Tag.objects.get(nombre_tag=nomTag)

        frase = Frase()

        try:
            frase = Frase.objects.get(id=idF)

            frase.tags.remove(tag)
            return HttpResponse("Tag borrado")
        except frase.DoesNotExist:
            return HttpResponse("error.")
    except tag.DoesNotExist:
        return HttpResponse("error.")

Lenguajes/Python/Django/djangoYPymongo/djangouser-master/DjangoM7/frasesmiticas/templates/frasesmiticas/addFrase.html
<form action="{% url 'frasesmiticas:postAddFrase' %}" method="post">
    {% csrf_token %}


    <h1>Introduce usuario y frase</h1>
    <fieldset>
        <label>user</label>
        <input type="text" name="user">
        <label>frase</label>
        <input type="text" name="frase">
    </fieldset>

    <input type="submit">
</form>

Lenguajes/Python/Django/djangoYPymongo/djangouser-master/DjangoM7/frasesmiticas/templates/frasesmiticas/addTag.html
<form action="{% url 'frasesmiticas:addTagPost' frase.id %}" method="post">
{% csrf_token %}
  <fieldset>
    {% if tags %}
    <p>Añadir tag a la frase {{frase.texto_frase}}</p>
      <ul>
        {% for tag in tags %}
          <!-- <li>{{ forloop.counter }} {{tag.nombre_tag}}</li> -->

          <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ tag.id }}">
          <label for="choice{{ forloop.counter }}">{{ tag.nombre_tag }}</label><br>

        {% endfor %}
      </ul>
    {% else %}
      <p> Pues eres tonto </p>
    {% endif %}
  </fieldset>
  <input type="submit" value="Vote">

</form>

Lenguajes/Python/Django/djangoYPymongo/djangouser-master/DjangoM7/frasesmiticas/templates/frasesmiticas/frasesDe.html
{% if frases %}
<p> Frases de {{usuario.username}} </p>
  <ul>
    {% for frase in frases %}
      <li>{{frase.texto_frase}}</li>
    {% endfor %}
  </ul>
{% else %}
  <p> Pues eres tonto </p>
{% endif %}